CREATE DATABASE reminder_app

USE reminder_app

CREATE TABLE INQUILINO(
	ID INT AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(100) NOT NULL,
    RENTA DECIMAL(10, 2) NOT NULL,
    PRIMARY KEY(ID)
)

CREATE TABLE RECORDATORIO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    PAGO DECIMAL(10, 2) NOT NULL,
    FECHA DATE NOT NULL,
    ID_ACUERDO INT NOT NULL,
    ESTA_PAGO BOOL NOT NULL,
    FOREIGN KEY (ID_ACUERDO) REFERENCES ACUERDO(ID)
)

CREATE TABLE ACUERDO(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    BALANCE DECIMAL (10,2) NOT NULL,
    ABONO DECIMAL (10,2) NOT NULL,
    ID_INQUILINO INT NOT NULL,
    FOREIGN KEY(ID_INQUILINO) REFERENCES INQUILINO(ID)
)

INSERT INTO INQUILINO (NOMBRE, APELLIDO, RENTA) 
VALUES ("JOSUE", "ESPINAL", 1200.00);

SELECT * FROM INQUILINO

INSERT INTO RECORDATORIO (PAGO, FECHA, ID_INQUILINO, ESTA_PAGO) 
VALUES (200.00,'2005-12-15',1,true);

SELECT * FROM RECORDATORIO

INSERT INTO ACUERDO (BALANCE, ABONO, ID_INQUILINO) VALUES 
(5000.00, 1000.00, 1);

SELECT * FROM ACUERDO;






