CREATE DATABASE reminder_app

USE reminder_app

CREATE TABLE INQUILINO(
	ID INT AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(100) NOT NULL,
    RENTA DECIMAL(10, 2) NOT NULL,
    PRIMARY KEY(ID)
)

CREATE TABLE RECORDATORIO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    PAGO DECIMAL(10, 2) NOT NULL,
    FECHA DATE NOT NULL,
    ID_INQUILINO INT NOT NULL,
    ESTA_PAGO BOOL NOT NULL,
    FOREIGN KEY (ID_INQUILINO) REFERENCES INQUILINO(ID)
)

CREATE TABLE ACUERDO(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    BALANCE DECIMAL (10,2) NOT NULL,
    ABONO DECIMAL (10,2) NOT NULL,
    ID_INQUILINO INT NOT NULL,
    FOREIGN KEY(ID_INQUILINO) REFERENCES INQUILINO(ID)
)



